// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNH-O1Xon-rED1Ej9LNaD_GoMHk8gyp9I',
    appId: '1:424047017295:web:27c74078cc2df816e9993a',
    messagingSenderId: '424047017295',
    projectId: 'bss-app-cf0c7',
    authDomain: 'bss-app-cf0c7.firebaseapp.com',
    storageBucket: 'bss-app-cf0c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAngHZ9Rfnmzghr7X9bCxnCa3qJ0eyAWeA',
    appId: '1:424047017295:android:428642d6e0ba7bb4e9993a',
    messagingSenderId: '424047017295',
    projectId: 'bss-app-cf0c7',
    storageBucket: 'bss-app-cf0c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9gYBPWVkKDOA_3U_r40jE0fS-grVjVo',
    appId: '1:424047017295:ios:36310431a6bdf3c8e9993a',
    messagingSenderId: '424047017295',
    projectId: 'bss-app-cf0c7',
    storageBucket: 'bss-app-cf0c7.appspot.com',
    iosClientId: '424047017295-9fk4e7h3m4t76hsb6j7vsjlv2n7bppk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bss',
  );
}
